apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  namespace: keycloak-db
  labels:
    app: keycloak-db
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app: keycloak-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
  namespace: keycloak-db
  labels:
    app: keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
      - name: keycloak-db
        image: quay.io/keycloak/keycloak:latest
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
        - name: DB_VENDOR
          value: MSSQL
        - name: DB_ADDR
          value: mssql-deployment.database
        - name: DB_DATABASE
          value: "keycloak"
        - name: DB_PORT
          value: "1433" 
        - name: DB_USER
          value: "sa" 
        - name: DB_PASSWORD
          value: "India@123"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
          initialDelaySeconds: 30	