kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-pvc
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
